// <auto-generated />
namespace DataGenerator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class lastupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201409161222425_lastupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
